### ISSUE TITLE
report cannot find name 'codeS20' after upgrade to 1.0.9

### ISSUE THREAD

**Issue by yoyo837** [JairusSW/json-as#133]
```ts
import { JSON } from 'json-as';

@json
export class SrvInfo {
  // accessUrl!: string;
  // cardTypes!: i32[];
  // customService!: string;
  // invoiceApplicationStatus!: i32;
  // isCertification!: bool;
  // isOnlineRecharge!: bool;
  // loginTypes!: i32[];
  // record!: string;
  // regCompanyAudit!: i32;
  // regCompanyPipeline!: i32[];
  // regPwdLimit!: i32;
  serverTime!: i64;
  // // srvAuths
  // srvDescription!: string;
  // srvHiddenMenu!: string[];
  // srvHost!: string;
  // srvId!: i32;
  // srvKeywords!: string[];
  // srvLogoImgUrl!: string;
  // srvName!: string;
  // srvPageId!: i32;
  // thirdAuthUrl!: string;
  // userCenterStyle!: i32;
}

@json
export class SportVenueConfig {
  salesItemId!: i32;
  bookStartTime!: i64;
  sliderCodeList!: i32[];
}

@json
class SalesItemVO {
  salesItemId!: i32;
  agreementRead!: i32;
  agreementUrl!: string;
  agreementTime!: i32;
}

@json
export class SalesItemConfig {
  salesItemVOList!: Array<SalesItemVO>;
}

export { JSON };

```

**Comment by JairusSW** [comment]
@yoyo837, thank you. I'm on it.
